services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14268"
      - "14250"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./.docker/prometheus.yml:/etc/prometheus/prometheus.yml
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    restart: always
    command: "--config=/etc/otel-collector-config.yml"
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OpenTelemetry gRPC receiver
      - "55678:55678"
    volumes:
      - ./.docker/otel-collector-config.yml:/etc/otel-collector-config.yml
  zipcode-service:
    build:
      context: .
      dockerfile: zipcode.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ZIPCODE_SERVER_PORT=:8080
      - WEATHER_SERVICE_URL=http://weather-service:8081/weather
    depends_on:
      - weather-service

  weather-service:
    build:
      context: .
      dockerfile: weather.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - WEB_SERVER_PORT=:8081
      - VIACEP_URL=https://viacep.com.br/ws/
      - WEATHERAPI_URL=http://api.weatherapi.com/v1/current.json
      - WEATHERAPI_KEY=your_api_key