services:
  zipcode-service:
    build:
      context: .
      dockerfile: zipcode.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ZIPCODE_SERVER_PORT=:8080
      - WEATHER_SERVICE_URL=http://weather-service:8081/weather
    depends_on:
      - weather-service

  weather-service:
    build:
      context: .
      dockerfile: weather.Dockerfile
    ports:
      - "8081:8081"
    environment:
      - WEB_SERVER_PORT=:8081
      - VIACEP_URL=https://viacep.com.br/ws/
      - WEATHERAPI_URL=http://api.weatherapi.com/v1/current.json
      - WEATHERAPI_KEY=your_api_key